# Generated by Django 4.0.5 on 2022-07-03 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='consumptionType_list',
            fields=[
                ('CoTypeId', models.IntegerField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='creditCard_type',
            fields=[
                ('credit', models.IntegerField(primary_key=True, serialize=False)),
                ('limit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='creditCardhistoryType_list',
            fields=[
                ('CeTypeId', models.IntegerField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('customer_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.creditcard_type')),
            ],
        ),
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('year_interest_rate', models.FloatField(default=0.045)),
                ('time_limit', models.IntegerField()),
                ('time', models.DateField()),
                ('loan_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.customer')),
            ],
        ),
        migrations.CreateModel(
            name='transactionType_list',
            fields=[
                ('TypeId', models.IntegerField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='transaction_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('time', models.DateField()),
                ('useCreditCard', models.BooleanField(default=False)),
                ('consumptionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.consumptiontype_list')),
                ('inAccount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inAccount', to='bank.account')),
                ('outAccount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outAccount', to='bank.account')),
                ('transactionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.transactiontype_list')),
            ],
        ),
        migrations.CreateModel(
            name='repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('time', models.DateField()),
                ('repayment_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.customer')),
                ('repayment_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.loan')),
            ],
        ),
        migrations.CreateModel(
            name='creditCard_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('amount', models.FloatField()),
                ('creditCardHistory_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.account')),
                ('creditCardhistoryType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.creditcardhistorytype_list')),
            ],
        ),
        migrations.CreateModel(
            name='credit_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_remain', models.FloatField()),
                ('creditcard_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.customer'),
        ),
    ]
