# Generated by Django 4.0.5 on 2022-07-03 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_bank_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_history',
            name='inAccount',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inAccount', to='bank.account'),
        ),
        migrations.AlterField(
            model_name='transaction_history',
            name='outAccount',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outAccount', to='bank.account'),
        ),
    ]
